version: "3.8"

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel-vue-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel-vue-nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel-vue-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  adminer:
    image: adminer:latest
    container_name: laravel-vue-adminer
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - laravel

  vite:
    image: node:23
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - VITE_SERVER=http://localhost:5173
    depends_on:
      - app


volumes:
  db-data:

networks:
  laravel:
