version: "3.8"

services:
  db:
    container_name: "db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  adminer:
    container_name: "adminer"
    image: adminer:latest
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - laravel

  app:
    container_name: "app"
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - db

  reverb:
    container_name: "reverb"
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:8080"
    user: "root"
    command: php artisan reverb:start --host=0.0.0.0
    networks:
      - laravel
    depends_on:
      - db

  vite:
    container_name: "vite"
    image: node:23
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - VITE_SERVER=http://localhost:5173
    depends_on:
      - app

  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - reverb
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
